### ISSUE TITLE
related issue for musinsago1.0

### ISSUE THREAD

**Issue by jakeyahn** [youngmki/musinsaigo#2]
Hi, I read your post from 'TensorFlow Korea' (or perhaps from 'PyTorch Korea,' not entirely sure), and tried to test the musinsago-1.0 model. By looking at the size of musinsago-1.0, which is 3.44 GB, I presume it is a fine-tuned DreamBooth model, not the LoRA model. Of course, when comparing the size to musinsago-2.0, which is 29.9MB, not in GB, I doubt the ver1.0 is surely not LoRA. 

Are you sure you used 'train_dreambooth_lora.py' or 'train_text_to_image_lora.py' for training musinsago-1.0, instead of 'train_dreambooth.py'?

I would appreciate your reply soon :)"

**Comment by youngmki** [comment]
Thank you for your question. MUSINSAIGO 1.0 was also fine-tuned with the LoRA technique. 

However, when I finally deployed the model, I uploaded it after forcing it to merge with the Stable Diffusion existing weights, so it has as much capacity as the original. 

For reference, I did the weight merging with the following code: https://github.com/youngmki/musinsaigo/blob/main/scripts/upload_models.py
